language: c

compiler:
  - gcc
  - clang

sudo: required

arch:
  packages:
    - qt5-declarative
    - extra-cmake-modules
    - kwallet
    - solid
    - networkmanager-qt
    - modemmanager-qt
    - pulseaudio
    - xorg-server-xvfb
    - git
    - clang
  script:
    - if [ "$CC" = "gcc" ]; then cmake . -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DCMAKE_INSTALL_PREFIX=/usr; fi
    - if [ "$CC" = "clang" ]; then cmake . -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DCMAKE_INSTALL_PREFIX=/usr; fi
    - make
    - sudo make install
    - xvfb-run -a -s "-screen 0 800x600x24" make check
    - ./.travis/bintray.sh

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

deploy:
  on: develop
  provider: bintray
  file: build/bintray.json
  user: plfiorini
  key:
    secure: AXgDeE2nJmBEMSU0zegjeesXkRE5Z5t3bW9w7tVxdwhlqiLv3UXLHiPazdkmxGWQDFhIIwSMz+BolpaTMRwYMOgPhzBahxYyHV5Q1yN4yn4XbwHqXegcpRzPuhHBidDaWJGJZJu6Wi2+CTTZ1WwEl8iXrHxqXs/4fy1GayUQEfg=

notifications:
  email: false
  slack: qmlos:fdUqVmPzqPskEL1UBhqapZ0w
