language: cpp

compiler:
  - gcc
#  - clang

cache:
  directories:
    - .cmake
    - .ecm
    - .qt
    - .glib

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

install:
  # gcc
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then export CC="gcc-4.8"; export CXX="g++-4.8"; fi
  # clang
  #- if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq clang-3.6; fi
  #- if [ "$CXX" == "clang++" ]; then export CC="clang-3.6"; export CXX="clang++-3.6"; fi

before_script:
  # Fetch and install dependencies if cache miss
  - curl https://raw.githubusercontent.com/hawaii-desktop/repotools/master/ci/fetch-deps | bash -x
  - bash -x .ci/fetch-deps
  - export PATH=`pwd`/.cmake/bin:`pwd`/.qt/5.6/bin:`pwd`/.glib/bin:$PATH
  # xvfb for unit tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # prepare
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test

notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#hawaii-desktop
    use_notice: true
    skip_join: true
    on_success: always
    on_failure: change
  slack:
    secure: EGWF118PTfBj/Oktmr20fc17JTM5gt7/j24k6HkiOI1J8S+sJyxhhtSjV54cgmsaEURJ7zUD/xi2wSSigi82k2F29wpELInfty/+j95vuY+7QO7nyVIINHjKranLUogKai9evHU2cvlNTq6e27pjkDbRO2HNKyzTb+Lb6D3VEOk=
    on_success: always
    on_failure: change
